version: "3"
services:
  rstudio: 
    build: "./rstudio_server"
    ports:
      - "8788:8787" # Tweak default port
    volumes:
      - .:/home/rstudio/odkitchen
    links:
      - selenium:selenium
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4445:4444"
