---
title: "How to create open data cooking recipes"
author: "Shinya Uryu"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Create Recipes}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 7.2,
  fig.height = 4,
  out.width = "100%"
)
```

```{r}
library(odkitchen)
library(testthat)
library(skimr)
library(tidyverse)
library(magrittr)
data("catalog")
```

## Collect Data

<!--TODO: flow chart -->

### Search from e-Stat catalog

```{r}
data_url <- catalog %>% 
  filter(str_detect(title, "木材流通")) %>% 
  tidyr::unnest() %>% 
  magrittr::use_series(url)
```

長期蓄積 「主要樹種別素材生産量累年統計」需要部門別 全国(昭和35年～平成25年) 

<https://www.e-stat.go.jp/stat-search/files?page=1&layout=datalist&toukei=00500219&tstat=000001015629&cycle=0&tclass1=000001034727&second2=1>

```{r, echo = TRUE, eval = FALSE}
library(RSelenium)
eCaps <- list(chromeOptions = list(
  prefs = list(
  "profile.default_content_settings.popups" = 0L,
  "download.prompt_for_download"            = FALSE,
  "download.default_directory"              = here::here("data-raw")
  )))
data_url <- "https://www.e-stat.go.jp/stat-search/files?page=1&layout=datalist&toukei=00500219&tstat=000001015629&cycle=0&tclass1=000001034727&second2=1"
  
RSelenium::rsDriver(port = 4444L)
remDr <- remoteDriver(port = 4444L, browserName = "chrome", extraCapabilities = eCaps)

# download_estat_excel(remDr, data_url) 要素の位置が異なるので以下を実行

remDr$open()
remDr$navigate(data_url)

webElem <- remDr$findElement("css selector", "div.stat-dataset_list > div > article:nth-child(98) > div > ul > li:nth-child(2) > div:nth-child(3) > div:nth-child(4) > div")
webElem$getElementText()
childElems <- webElem$findChildElements("css selector", "span")

childElems[[1]]$clickElement()
remDr$close()
```

## Data Wrangling

### Import

```{r}
# check open excel ahead of time 
df_raw <- readxl::read_excel(
  here::here("data-raw", "f010c-003-001-000-000.xls"),
  sheet = 1, 
  range = c("A6:CA63"),
  na = c("", "…", "-"))
comment(df_raw) <- "主要樹種別素材生産量累年統計"

test_that(
  "raw-data", {
    expect_equal(dim(df_raw), c(57, 79))
  }
)
```

### Modified raw data

```{r}
names(df_raw)

# use this!
(column_names_part1 <- names(df_raw)[!str_detect(names(df_raw), "X__")])
```

```{r}
# extract true column names
(column_names_part2 <- df_raw[1, ] %>% 
  # remove readxl defalt names
  .[1, ] %>% set_names(NULL) %>% as_vector() %>% 
  unique() %>% na.omit())
attributes(column_names_part2) <- NULL


column_names_part3 <- df_raw[2, ] %>% 
    #select_if(all_vars(!is.na(.))) %>% 
  .[1, ] %>% set_names(NULL) %>% as_vector() %>% 
  unique() %>% na.omit()
attributes(column_names_part3) <- NULL

column_names_part3 <- c(column_names_part3[length(column_names_part3)], column_names_part3[1:length(column_names_part3)- 1])


# repeat N times
# (column_names_n_times <- x %>% str_count("製材用") %>% sum())
```

```{r}
# Combine names
# dplyr::coalesce?
x <- !str_detect(names(df_raw), "X__")
x <- x %>% as.numeric()

x <- x %>% 
  str_replace("0", NA_character_)
```

```{r}
# TODO: more readable coding 
long_colnames <- c(column_names_part1[1],
  column_names_part1[2],
  paste(column_names_part1[2], column_names_part3[2:length(column_names_part3)], sep = "_"),
  rep(paste(column_names_part1[3], 
            paste(rep(column_names_part2[1:8], each = length(column_names_part3)), column_names_part3, sep = "_"), sep = "_")),
  rep(paste(column_names_part1[4], 
            paste(rep(column_names_part2[c(1, 9, 10, 8)], each = length(column_names_part3)),
            column_names_part3, sep = "_"), sep = "_")))

expect_equal(
  df_raw %>% names() %>% length(),
  long_colnames %>% length()
)
```

```{r}
# convert japanese year to YYYY (as Integer)
df_raw[4, 1] %>% stringr::str_extract("\\(.+\\)") %>% 
  str_replace_all("[:punct:]", "") %>% 
  as.integer()
```


```{r}
# extract unit vars
columun_units <- df_raw[3, ] %>% as.character()
# Convert with units package
df_raw[4, 2] %>% as.numeric() %>% units::set_units("cBm")
convert_vars_at <- which(!is.na(columun_units))

test_that(
  "units", {
    expect_length(na.omit(unique(columun_units)), 1L)  
    expect_equal(range(convert_vars_at), c(2, 79))
    expect_length(convert_vars_at, 78)
  }
)
```

```{r}
df_modified <- df_raw %>% 
  slice(-1:-3) %>% 
  set_names(long_colnames) %>% 
  mutate_at(1, funs(stringr::str_extract(., "\\(.+\\)") %>% 
  str_replace_all("[:punct:]", "") %>% 
  as.integer())) %>% 
  # readr::type_convert() %>% 
  mutate_at(vars(c(-1)), as.numeric) %>% 
  # add unit attributes
  mutate_at(vars(c(convert_vars_at)), funs(units::set_units(., "cBm")))

test_that(
  "modified_data", {
    expect_equal(dim(df_modified), c(54, 79))
    
    expect_is(df_modified$年次, "integer")
    
    expect_s3_class(df_modified$計[1], "units")
    expect_identical(df_modified$計[1], units::set_units(48515, cBm))
  }
)
```

EDA

```{r, eval = FALSE, echo = FALSE}
visdat::vis_miss(df_modified[, c(2:7)])

df_modified %>%
  select(starts_with("針葉樹_小計")) %>%
  visdat::vis_miss()

df_modified %>%
  select(starts_with("広葉樹_小計")) %>%
  naniar::gg_miss_var(show_pct = TRUE)


df_modified %>% skimr::skim()
```

## Summarise and Visualization

```{r}
library(ggforce)
df_modified %>% 
  ggplot(aes(`年次`, `計`)) + geom_line()
```

```{r}
df_year_type <- df_modified %>% 
  select(`年次`, starts_with("計_")) %>% 
  tidyr::gather(type, value, -`年次`)

df_year_type %>% 
  ggplot(aes(`年次`, value, colour = type)) + 
  geom_line() +
  scale_x_unit(unit = "cBm")
```

```{r}
df_year_type %>%
  group_by(type) %>% 
  summarise(value = sum(value, na.rm = TRUE)) %>% 
  ggplot(aes(type, value)) + 
  geom_bar(stat = "identity")
```

