FROM rocker/binder:latest
MAINTAINER "Shinya Uryu" <r.sh1nya.uryu@gmail.com>

RUN Rscript -e 'install.packages(c("config", "drake", "estatapi", "ggforce", "here", "hrbrthemes", "jpmesh", "jpndistrict", "naniar", "RSelenium", "skimr"))'
