version: "3"
services:
  binder:  
    # image: rocker/binder:latest
    # image: uribo/odkitchen_binder
    build: "./binder"
    ports:
      - "8888:8888"
    volumes:
      - ../.:/home/rstudio/odkitchen
