version: "3"
services:
  rstudio: 
    image: uribo/odkitchen
    # build: "./rstudio_server"
    ports:
      - "8788:8787" # Tweak default port
    volumes:
      - ../.:/home/rstudio/odkitchen
  binder:  
    # image: rocker/binder:latest
    image: uribo/odkitchen_binder
    # build: "./binder"
    ports:
      - "8888:8888"
    volumes:
      - ../.:/home/rstudio/odkitchen
