FROM uribo/tiny_rocker_geospatial:latest
MAINTAINER "Shinya Uryu" <r.sh1nya.uryu@gmail.com>

RUN install2.r \
  caTools \ # for rmarkdown
  config drake estatapi here hrbrthemes jpmesh jpndistrict \
  liftr RSelenium
